name: second CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, from second workflow"

      - name: Install
        env:
          APP_ENV: dev
          DB_PASS: ${{secrets.DB_PASS}}
        run: echo "Environment $APP_ENV using $DB_PASS"

      - name: Create demo file
        run: |
          echo "This is a demo file" > demo.txt
          echo "This is a demo2 file" > demo2.txt
      
      - name : Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact-demo
          path: .